---
abstract: "Utility for word cloud.\r"
author:
  - "Naoki Okamura (Nyarla) <nyarla[:)]thotep.net>\r"
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.8
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Cloud
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
