--- 
abstract: Utility for word cloud.
author: 
  - Naoki Okamura (Nyarla) <thotep@nayrla.net>
build_requires: 
  Test::More: 0.8
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Cloud
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
tests: t/*.t
version: 0.02
